name: Build and deploy docs

env:
  BUILD_BRANCH_NAME: build

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"
      - name: Install dependencies
        run: poetry install
      - name: Build docs
        run: poetry run mkdocs build
      - name: Upload docs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: site/

  push-docs:
    runs-on: ubuntu-latest
    needs: build-and-deploy-docs
    permissions:
      contents: write
    steps:
      - name: Checkout existing branch
        uses: actions/checkout@v4
        id: checkout-existing
        continue-on-error: true
        with:
          ref: ${{ env.BUILD_BRANCH_NAME }}
      - name: Default checkout
        uses: actions/checkout@v4
        if: steps.checkout-existing.outcome == 'failure'
      - name: Setup repository
        shell: bash
        run: |
          git checkout ${{ env.BUILD_BRANCH_NAME }} 2>/dev/null || git checkout --orphan ${{ env.BUILD_BRANCH_NAME }}
          git config user.name "Push to branch action"
          git config user.email "${{ github.actor || 'push-to-branch-action' }}@users.noreply.github.com"
          git rm -rf '*'
      - name: Download docs
        uses: actions/download-artifact@v4
        with:
          name: docs
      - name: Push to remote
        shell: bash
        run: |
          git add --all .
          git commit --no-verify -m "Deploying from @ ${{ github.sha }}" && git push -u origin ${{ env.BUILD_BRANCH_NAME }} || true
